"""Adds search filter and entity triggers

Revision ID: 61a861559de9
Revises: d089d1d110f0
Create Date: 2023-04-10 11:57:54.896708

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import MetaData

from dispatch.search.fulltext import sync_trigger

# revision identifiers, used by Alembic.
revision = "61a861559de9"
down_revision = "d089d1d110f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_context().connection
    # env.py sets search_path per tenant *after* connecting, and the dialect
    # caches default_schema_name from the first connection for the engine's
    # whole lifetime, so it reads "public" here no matter which schema is
    # active. current_schema() reflects the live search_path instead.
    schema = conn.exec_driver_sql("SELECT current_schema()").scalar()
    metadata = MetaData(schema=schema)
    table = sa.Table("entity_type", metadata, autoload_with=conn)
    sync_trigger(conn, table, "search_vector", ["name", "description"])
    table = sa.Table("signal_filter", metadata, autoload_with=conn)
    sync_trigger(conn, table, "search_vector", ["name", "description"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
